apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld-devops-stack
  name: helloworld-devops-stack-clusterip
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: helloworld-http
  selector:
    app: helloworld-devops-stack
  type: ClusterIP
