apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld-devops-stack
  name: helloworld-devops-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-devops-stack
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: lentidas/helloworld-devops-stack:0.0.1-alpha
        name: helloworld-devops-stack-nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
