apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "devops-stack-helloworld.labels" $ | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "devops-stack-helloworld.selector" $ | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "devops-stack-helloworld.labels" $ | indent 8 }}
    spec:
      # Mount a volume containing the ConfigMap with the generated hyperlinks
      volumes:
      - name: commands-configmap
        configMap:
          name: {{ .Chart.Name }}-hyperlinks-configmap

      containers:

      # nginx-based container containing the helloworld static page
      - image: ghcr.io/lentidas/lentidas/devops-stack-helloworld:latest # TODO change image here after transfering ownership of the repository
        name: helloworld
        ports:
        - containerPort: 80
          name: helloworld-http
          protocol: TCP
        - containerPort: 8080
          name: stub-status
          protocol: TCP
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: commands-configmap
          mountPath: /usr/share/nginx/html/src/js/hyperlinks.js
          subPath: hyperlinks.js
      
      # nginx-exporter to parse the metrics in a readable format for Prometheus
      - image: nginx/nginx-prometheus-exporter:latest
        name: metrics
        args:
        - "-nginx.scrape-uri=http://localhost:8080/stub_status" # Point to the port 8080 inside this pod that is served by the container above
        ports:
        - containerPort: 9113
          protocol: TCP
          name: metrics
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
