apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld-devops-stack
  name: helloworld-devops-stack-clusterip
spec:
  ports:
  - name: helloworld-http
    port: 8080
    protocol: TCP
    targetPort: helloworld-http
  - name: metrics
    port: 9113
    protocol: TCP
    targetPort: metrics
  selector:
    app: helloworld-devops-stack
  type: ClusterIP
