apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-clusterip
  labels:
    {{- include "devops-stack-helloworld.labels" $ | indent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "devops-stack-helloworld.selector" $ | indent 4 }}
  ports:
  - name: helloworld-http
    port: 8080
    protocol: TCP
    targetPort: helloworld-http
  - name: metrics
    port: 9113
    protocol: TCP
    targetPort: metrics
