apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-stack-helloworld
  name: devops-stack-helloworld-clusterip
spec:
  ports:
  - name: helloworld-http
    port: 8080
    protocol: TCP
    targetPort: helloworld-http
  - name: metrics
    port: 9113
    protocol: TCP
    targetPort: metrics
  selector:
    app: devops-stack-helloworld
  type: ClusterIP
