apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: devops-stack-helloworld
  name: devops-stack-helloworld-servicemonitor
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - helloworld
  selector:
    matchLabels:
      app: devops-stack-helloworld
