---
# HTTPS Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.cluster.issuer }}
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.allow-http: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  name: {{ .Chart.Name }}-ingress
spec:
  rules:
  - host: "helloworld.{{ printf "%s.%s.%s" .Values.cluster.subdomain .Values.cluster.name .Values.cluster.domain | trimPrefix "." }}"
    http:
      paths:
      - backend:
          service:
            name: {{ .Chart.Name }}-clusterip
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - "helloworld.{{ printf "%s.%s.%s" .Values.cluster.subdomain .Values.cluster.name .Values.cluster.domain | trimPrefix "." }}"
    secretName: devops-stack-helloworld-ingress-tls-cert
