apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-stack-helloworld
  name: devops-stack-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-stack-helloworld
  template:
    metadata:
      labels:
        app: devops-stack-helloworld
    spec:
      containers:

      # nginx-based container containing the helloworld static page
      - image: lentidas/helloworld-devops-stack:0.0.2-alpha
        name: helloworld
        ports:
        - containerPort: 80
          name: helloworld-http
          protocol: TCP
        - containerPort: 8080
          name: stub-status
          protocol: TCP
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      
      # nginx-exporter to parse the metrics in a readable format for Prometheus
      - image: nginx/nginx-prometheus-exporter:latest
        name: metrics
        args:
        - "-nginx.scrape-uri=http://localhost:8080/stub_status" # Point to the port 8080 inside this pod that is served by the container above
        ports:
        - containerPort: 9113
          protocol: TCP
          name: metrics
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

