apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{ include "devops-stack-helloworld.labels" . | indent 4 }}
  name: {{ .Chart.Name }}-servicemonitor
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{ include "devops-stack-helloworld.selector" . | indent 6 }}
