apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-hyperlinks-configmap
  labels:
    {{- include "devops-stack-helloworld.labels" $ | indent 4 }}
data:
  hyperlinks.js: |-
    const lists = [
      {
        heading: 'Applications',
        links: [
          {
            title: 'Argo CD',
            url: 'https://argocd.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}/',
          },
          {{- if .Values.apps.traefik_dashboard }}
          {
            title: 'Traefik Dashboard',
            url: 'https://traefik.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}/',
          },
          {{ end -}}
          {{- if .Values.apps.grafana }}
          {
            title: 'Grafana',
            url: 'https://grafana.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}/',
          },
          {{ end -}}
          {{- if .Values.apps.thanos }}
          {
            title: 'Thanos Query',
            url: 'https://thanos-query.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}/',
          },
          {
            title: 'Thanos Bucketweb',
            url: 'https://thanos-bucketweb.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}/',
          },
          {{ end -}}
          {{- if .Values.apps.prometheus }}
          {
            title: 'Prometheus',
            url: 'https://prometheus.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}/',
          },
          {{ end -}}
          {{- if .Values.apps.alertmanager }}
          {
            title: 'Alertmanager',
            url: 'https://alertmanager.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.domain }}/',
          },
          {{ end -}}
        ],
      },
      {
        heading: 'DevOps Stack',
        links: [
          {
            title: 'About',
            url: 'https://devops-stack.io/',
          },
          {
            title: 'Documentation',
            url: 'https://devops-stack.io/docs/latest/',
          },
          {
            title: 'Repository',
            url: 'https://github.com/camptocamp/devops-stack',
          },
        ],
      },
      {
        heading: 'Our Company',
        links: [
          {
            title: 'Camptocamp',
            url: 'https://www.camptocamp.com/',
          },
        ],
      },
    ]

    function renderLists() {
      const linksWrapper = document.querySelector('#links')

      lists.forEach(list => {
          const linksTemplate = list.links.map(link => {
              return `
          <li class="links__item">
            <a class="links__link" href="${link.url}">${link.title}</a>
          </li>
        `
          })

          const template = `
        <ul class="links">
          <li class="links__item">
            <span class="links__heading">${list.heading}</span>
          </li>
          ${linksTemplate.join('')}
        </ul>
      `

          linksWrapper.insertAdjacentHTML('beforeend', template)
      })
    }

    renderLists()
