apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "devops-stack-helloworld.labels" $ | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "devops-stack-helloworld.selector" $ | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "devops-stack-helloworld.labels" $ | indent 8 }}
      annotations:
        # Compute hash of the the configuration passed to define the links inside the static page
        helloworld-configmap-checksum: {{ include (print $.Template.BasePath "/helloworld_hyperlinks_configmap.yaml") . | sha256sum | trunc 32 }}
    spec:
      # Mount a volume containing the ConfigMap with the generated hyperlinks
      volumes:
      - name: hyperlinks-configmap
        configMap:
          name: {{ .Chart.Name }}-hyperlinks-configmap

      containers:

      # nginx-based container containing the helloworld static page
      - image: {{ .Values.image }}
        name: helloworld
        ports:
        - containerPort: 80
          name: helloworld-http
          protocol: TCP
        - containerPort: 8080
          name: stub-status
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        volumeMounts:
        - name: hyperlinks-configmap
          mountPath: /usr/share/nginx/html/assets/js/hyperlinks.js
          subPath: hyperlinks.js
      
      # nginx-exporter to parse the metrics in a readable format for Prometheus
      - image: nginx/nginx-prometheus-exporter:latest
        name: metrics
        args:
        - "-nginx.scrape-uri=http://localhost:8080/stub_status" # Point to the port 8080 inside this pod that is served by the container above
        ports:
        - containerPort: 9113
          protocol: TCP
          name: metrics
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
