apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld-devops-stack
  name: helloworld-devops-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-devops-stack
  template:
    metadata:
      labels:
        app: helloworld-devops-stack
    spec:
      containers:
      - image: lentidas/helloworld-devops-stack:0.0.2-alpha
        name: helloworld
        ports:
        - containerPort: 80
          name: helloworld-http
          protocol: TCP
        - containerPort: 8080
          name: stub-status
          protocol: TCP
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - image: nginx/nginx-prometheus-exporter:latest
        name: metrics
        args:
        - "-nginx.scrape-uri=http://localhost:8080/stub_status"
        ports:
        - containerPort: 9113
          protocol: TCP
          name: metrics
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

